<?php

########################################################################
# Extension Manager/Repository config file for ext: "blogger"
#
# Auto generated by Extension Builder 2011-12-22
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Blogger',
	'description' => 'Komplex but easy blog system with extbase / fluid base',
	'category' => 'plugin',
	'author' => 'Tim Lochmüller',
	'author_email' => 'tl@hdnet.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'tagger' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>